#### general settings
name: UDC_Res5_Pix_1024x1024
use_tb_logger: true
model: sr
distortion: sr
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: Poled
    mode: LQGT
    dataroot_GT: /data0/Shop_DATA/Poled/Poled_train_HQ.lmdb
    dataroot_LQ: /data0/Shop_DATA/Poled/Poled_train_LQ.lmdb

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 4
    GT_size: 1024
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Poled_val30
    mode: LQGT
    dataroot_GT: /data0/Shop_DATA/Poled_val/HQ
    dataroot_LQ: /data0/Shop_DATA/Poled_val/LQ

#### network structures
network_G:
  which_model_G: UDC_res_5 # UDC_SRRes | UDC_Unet_decoder_3x3_onIN_encoder_8HW
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 16
  upscale: 4

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: 0.0001
  lr_scheme: MultiStepLR    # CosineAnnealingLR_Restart | MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 70000
  warmup_iter: -1  # no warm up
  
  lr_steps: [10000, 20000, 30000, 40000, 50000]
  lr_gamma: 0.5
  
  #T_period: [250000, 250000, 250000, 250000]
  #restarts: [250000, 500000, 750000]
  
  
  #restart_weights: [1, 1, 1]
  eta_min: 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 1e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3